---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - heimdall-data:/config
    ports:
      - 5080:80
      - 5443:443
    restart: unless-stopped

volumes:
 heimdall-data: