version: '2'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=PASSWORD
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=PASSWORD
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:21.12.1
    depends_on:
    - mysql
    restart: always
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=PASSWORD
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
    - APP_URL=https://wiki.example.com
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.bookstack.rule=Host(`wiki.example.com`)"
    - "traefik.http.services.bookstack.loadBalancer.server.port=8080"
    - "traefik.http.routers.bookstack.entrypoints=websecure"
    - "traefik.http.routers.bookstack.tls=true"
    - "traefik.http.routers.bookstack.tls.certresolver=production"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
 
networks:
  default:
    external:
      name: traefik-stack_default

