# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: exampleuser
    ports:
      - 5433:5432
  teamcity:
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - 8111:8111
      - 6443:6443
    volumes:
      - teamcity_logs:/opt/teamcity/logs
      - teamcity_data:/data/teamcity_server/datadir
volumes:
 teamcity_logs:
 teamcity_data: